// Run: node build-content.js
// Reads all THE100 markdown files and generates content.js

const fs = require('fs');
const path = require('path');

const SRC = 'C:/Users/admin/iCloudDrive/iCloud~md~obsidian/A/wiki/_work/THE100';
const OUT = path.join(__dirname, 'content.js');

const files = fs.readdirSync(SRC).filter(f => f.endsWith('.md')).sort();

const content = {};

for (const file of files) {
  const m = file.match(/THE100-(\d+)/);
  if (!m) continue;
  const rank = parseInt(m[1], 10);
  const text = fs.readFileSync(path.join(SRC, file), 'utf8');
  content[rank] = text;
}

const js = `// Auto-generated by build-content.js — do not edit manually
const CONTENT = ${JSON.stringify(content, null, 0)};
`;

fs.writeFileSync(OUT, js, 'utf8');
console.log(`Generated content.js with ${Object.keys(content).length} entries.`);
