// Auto-generated by build-data.js — do not edit manually
const PERSONS = [
  {
    "rank": 1,
    "zh": "穆罕默德",
    "en": "Muhammad",
    "birth": 570,
    "death": 632,
    "birth_lat": 21.4,
    "birth_lng": 38.8,
    "region": "西亚",
    "countries": [
      "SA"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual",
      "role/Society/Governance/Politician"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": "https://docs.suphy.top/file/Muhammad_Calligraphic.svg"
  },
  {
    "rank": 2,
    "zh": "牛顿",
    "en": "Isaac Newton",
    "birth": 1642,
    "death": 1727,
    "birth_lat": 52.8,
    "birth_lng": -0.6,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Physicist",
      "role/Nature/Science/Mathematician"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 3,
    "zh": "耶稣基督",
    "en": "Jesus Christ",
    "birth": -6,
    "death": 30,
    "birth_lat": 31.7,
    "birth_lng": 35.2,
    "region": "西亚",
    "countries": [
      "PS"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  },
  {
    "rank": 4,
    "zh": "释迦牟尼",
    "en": "Buddha",
    "birth": -563,
    "death": -483,
    "birth_lat": 27.5,
    "birth_lng": 83.3,
    "region": "南亚",
    "countries": [
      "IN",
      "NP"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  },
  {
    "rank": 5,
    "zh": "孔子",
    "en": "Confucius",
    "birth": -551,
    "death": -479,
    "birth_lat": 35.6,
    "birth_lng": 117,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 6,
    "zh": "圣保罗",
    "en": "St. Paul",
    "birth": 4,
    "death": 64,
    "birth_lat": 36.9,
    "birth_lng": 34.9,
    "region": "西亚",
    "countries": [
      "TR",
      "IT"
    ],
    "tags": [
      "role/Spirit/Religion/Theologian",
      "role/Spirit/Religion/Clergy",
      "role/Spirit/Creative/Author"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Theologian",
    "img": null
  },
  {
    "rank": 7,
    "zh": "蔡伦",
    "en": "Ts'ai Lun",
    "birth": 50,
    "death": 121,
    "birth_lat": 26,
    "birth_lng": 112,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 8,
    "zh": "古登堡",
    "en": "Johann Gutenberg",
    "birth": 1400,
    "death": 1468,
    "birth_lat": 50,
    "birth_lng": 8.3,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 9,
    "zh": "哥伦布",
    "en": "Christopher Columbus",
    "birth": 1451,
    "death": 1506,
    "birth_lat": 44.4,
    "birth_lng": 8.9,
    "region": "南欧",
    "countries": [
      "IT",
      "ES"
    ],
    "tags": [
      "role/Society/Frontier/Explorer"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Explorer",
    "img": null
  },
  {
    "rank": 10,
    "zh": "爱因斯坦",
    "en": "Albert Einstein",
    "birth": 1879,
    "death": 1955,
    "birth_lat": 48.4,
    "birth_lng": 10,
    "region": "西欧",
    "countries": [
      "DE",
      "CH",
      "US"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": "https://docs.suphy.top/file/Einstein1.svg"
  },
  {
    "rank": 11,
    "zh": "巴斯德",
    "en": "Louis Pasteur",
    "birth": 1822,
    "death": 1895,
    "birth_lat": 47.1,
    "birth_lng": 5.5,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Nature/Science/Biologist",
      "role/Nature/Science/Chemist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Biologist",
    "img": null
  },
  {
    "rank": 12,
    "zh": "伽利略",
    "en": "Galileo Galilei",
    "birth": 1564,
    "death": 1642,
    "birth_lat": 43.7,
    "birth_lng": 10.4,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Nature/Science/Astronomer",
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Astronomer",
    "img": null
  },
  {
    "rank": 13,
    "zh": "亚里士多德",
    "en": "Aristotle",
    "birth": -384,
    "death": -322,
    "birth_lat": 40.5,
    "birth_lng": 23.7,
    "region": "南欧",
    "countries": [
      "GR"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Aristotle_Altemps_Inv8575.jpg"
  },
  {
    "rank": 14,
    "zh": "欧几里得",
    "en": "Euclid",
    "birth": -300,
    "death": -250,
    "birth_lat": 31.2,
    "birth_lng": 29.9,
    "region": "南欧",
    "countries": [
      "GR"
    ],
    "tags": [
      "role/Nature/Science/Mathematician"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Mathematician",
    "img": null
  },
  {
    "rank": 15,
    "zh": "摩西",
    "en": "Moses",
    "birth": -1330,
    "death": -1250,
    "birth_lat": 30.1,
    "birth_lng": 31.2,
    "region": "北非",
    "countries": [
      "EG",
      "PS"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  },
  {
    "rank": 16,
    "zh": "达尔文",
    "en": "Charles Darwin",
    "birth": 1809,
    "death": 1882,
    "birth_lat": 52.7,
    "birth_lng": -2.8,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Biologist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Biologist",
    "img": null
  },
  {
    "rank": 17,
    "zh": "秦始皇",
    "en": "Shih Huang Ti",
    "birth": -259,
    "death": -210,
    "birth_lat": 34.4,
    "birth_lng": 113.7,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 18,
    "zh": "奥古斯都",
    "en": "Augustus Caesar",
    "birth": -63,
    "death": 14,
    "birth_lat": 41.9,
    "birth_lng": 12.5,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 19,
    "zh": "哥白尼",
    "en": "Nicolaus Copernicus",
    "birth": 1473,
    "death": 1543,
    "birth_lat": 53,
    "birth_lng": 18.6,
    "region": "东欧",
    "countries": [
      "PL"
    ],
    "tags": [
      "role/Nature/Science/Astronomer"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Astronomer",
    "img": null
  },
  {
    "rank": 20,
    "zh": "拉瓦锡",
    "en": "Antoine Laurent Lavoisier",
    "birth": 1743,
    "death": 1794,
    "birth_lat": 48.9,
    "birth_lng": 2.3,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Nature/Science/Chemist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Chemist",
    "img": null
  },
  {
    "rank": 21,
    "zh": "君士坦丁大帝",
    "en": "Constantine the Great",
    "birth": 280,
    "death": 337,
    "birth_lat": 43.3,
    "birth_lng": 21.9,
    "region": "南欧",
    "countries": [
      "RS",
      "TR"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 22,
    "zh": "瓦特",
    "en": "James Watt",
    "birth": 1736,
    "death": 1819,
    "birth_lat": 55.9,
    "birth_lng": -4.8,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 23,
    "zh": "迈克尔·法拉第",
    "en": "Michael Faraday",
    "birth": 1791,
    "death": 1867,
    "birth_lat": 51.5,
    "birth_lng": -0.1,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 24,
    "zh": "麦克斯韦",
    "en": "James Clerk Maxwell",
    "birth": 1831,
    "death": 1879,
    "birth_lat": 55.9,
    "birth_lng": -3.2,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 25,
    "zh": "路德",
    "en": "Martin Luther",
    "birth": 1483,
    "death": 1546,
    "birth_lat": 51.5,
    "birth_lng": 11.5,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Spirit/Religion/Theologian"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Theologian",
    "img": null
  },
  {
    "rank": 26,
    "zh": "乔治·华盛顿",
    "en": "George Washington",
    "birth": 1732,
    "death": 1799,
    "birth_lat": 38.3,
    "birth_lng": -77.5,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 27,
    "zh": "卡尔·马克思",
    "en": "Karl Marx",
    "birth": 1818,
    "death": 1883,
    "birth_lat": 49.8,
    "birth_lng": 6.6,
    "region": "西欧",
    "countries": [
      "DE",
      "GB"
    ],
    "tags": [
      "role/Spirit/Humanities/SocialScientist"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "SocialScientist",
    "img": null
  },
  {
    "rank": 28,
    "zh": "莱特兄弟",
    "en": "Orville and Wilbur Wright",
    "birth": 1867,
    "death": 1948,
    "birth_lat": 39.8,
    "birth_lng": -84.2,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 29,
    "zh": "成吉思汗",
    "en": "Genghis Khan",
    "birth": 1162,
    "death": 1227,
    "birth_lat": 48,
    "birth_lng": 105,
    "region": "东亚",
    "countries": [
      "MN"
    ],
    "tags": [
      "role/Society/Frontier/Conqueror"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Conqueror",
    "img": null
  },
  {
    "rank": 30,
    "zh": "亚当·斯密",
    "en": "Adam Smith",
    "birth": 1723,
    "death": 1790,
    "birth_lat": 56.1,
    "birth_lng": -3.2,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Spirit/Humanities/SocialScientist"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "SocialScientist",
    "img": null
  },
  {
    "rank": 31,
    "zh": "莎士比亚",
    "en": "Edward de Vere",
    "birth": 1550,
    "death": 1604,
    "birth_lat": 52.2,
    "birth_lng": -1.7,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Spirit/Creative/Author"
    ],
    "domain": "Spirit",
    "category": "Creative",
    "role": "Author",
    "img": null
  },
  {
    "rank": 32,
    "zh": "约翰·道尔顿",
    "en": "John Dalton",
    "birth": 1766,
    "death": 1844,
    "birth_lat": 54.7,
    "birth_lng": -3.3,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Chemist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Chemist",
    "img": null
  },
  {
    "rank": 33,
    "zh": "亚历山大大帝",
    "en": "Alexander the Great",
    "birth": -356,
    "death": -323,
    "birth_lat": 40.8,
    "birth_lng": 22.5,
    "region": "南欧",
    "countries": [
      "GR"
    ],
    "tags": [
      "role/Society/Frontier/Conqueror"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Conqueror",
    "img": null
  },
  {
    "rank": 34,
    "zh": "拿破仑·波拿巴",
    "en": "Napoleon Bonaparte",
    "birth": 1769,
    "death": 1821,
    "birth_lat": 41.9,
    "birth_lng": 8.7,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Society/Governance/General"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "General",
    "img": null
  },
  {
    "rank": 35,
    "zh": "托马斯·爱迪生",
    "en": "Thomas Edison",
    "birth": 1847,
    "death": 1931,
    "birth_lat": 41.4,
    "birth_lng": -82.4,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": "https://docs.suphy.top/file/ThomasEdison.png"
  },
  {
    "rank": 36,
    "zh": "安东尼·范·列文虎克",
    "en": "Antony van Leeuwenhoek",
    "birth": 1632,
    "death": 1723,
    "birth_lat": 52,
    "birth_lng": 4.4,
    "region": "西欧",
    "countries": [
      "NL"
    ],
    "tags": [
      "role/Nature/Science/Biologist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Biologist",
    "img": null
  },
  {
    "rank": 37,
    "zh": "威廉·莫顿",
    "en": "William T. G. Morton",
    "birth": 1819,
    "death": 1868,
    "birth_lat": 42,
    "birth_lng": -71.3,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Nature/Science/Doctor"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Doctor",
    "img": null
  },
  {
    "rank": 38,
    "zh": "马可尼",
    "en": "Guglielmo Marconi",
    "birth": 1874,
    "death": 1937,
    "birth_lat": 44.5,
    "birth_lng": 11.3,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 39,
    "zh": "希特勒",
    "en": "Adolf Hitler",
    "birth": 1889,
    "death": 1945,
    "birth_lat": 48.3,
    "birth_lng": 13,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 40,
    "zh": "柏拉图",
    "en": "Plato",
    "birth": -427,
    "death": -347,
    "birth_lat": 37.9,
    "birth_lng": 23.7,
    "region": "南欧",
    "countries": [
      "GR"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 41,
    "zh": "克伦威尔",
    "en": "Oliver Cromwell",
    "birth": 1599,
    "death": 1658,
    "birth_lat": 52.3,
    "birth_lng": -0.2,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Society/Governance/General"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "General",
    "img": null
  },
  {
    "rank": 42,
    "zh": "亚历山大·贝尔",
    "en": "Alexander Graham Bell",
    "birth": 1847,
    "death": 1922,
    "birth_lat": 55.9,
    "birth_lng": -3.2,
    "region": "北欧",
    "countries": [
      "GB",
      "US"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 43,
    "zh": "亚历山大·弗莱明",
    "en": "Alexander Fleming",
    "birth": 1881,
    "death": 1955,
    "birth_lat": 55.6,
    "birth_lng": -4.3,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/MedResearcher"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "MedResearcher",
    "img": null
  },
  {
    "rank": 44,
    "zh": "洛克",
    "en": "John Locke",
    "birth": 1632,
    "death": 1704,
    "birth_lat": 51.3,
    "birth_lng": -2.8,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 45,
    "zh": "贝多芬",
    "en": "Ludwig van Beethoven",
    "birth": 1770,
    "death": 1827,
    "birth_lat": 50.7,
    "birth_lng": 7.1,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Spirit/Creative/Composer"
    ],
    "domain": "Spirit",
    "category": "Creative",
    "role": "Composer",
    "img": null
  },
  {
    "rank": 46,
    "zh": "海森堡",
    "en": "Werner Heisenberg",
    "birth": 1901,
    "death": 1976,
    "birth_lat": 49.8,
    "birth_lng": 9.9,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 47,
    "zh": "路易·达盖尔",
    "en": "Louis Daguerre",
    "birth": 1787,
    "death": 1851,
    "birth_lat": 49.2,
    "birth_lng": 0.4,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 48,
    "zh": "玻利瓦尔",
    "en": "Simon Bolivar",
    "birth": 1783,
    "death": 1830,
    "birth_lat": 10.5,
    "birth_lng": -66.9,
    "region": "南美",
    "countries": [
      "VE"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 49,
    "zh": "笛卡尔",
    "en": "Rene Descartes",
    "birth": 1596,
    "death": 1650,
    "birth_lat": 46.7,
    "birth_lng": 0.8,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 50,
    "zh": "米开朗基罗",
    "en": "Michelangelo",
    "birth": 1475,
    "death": 1564,
    "birth_lat": 43.6,
    "birth_lng": 11.9,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Spirit/Creative/Artist"
    ],
    "domain": "Spirit",
    "category": "Creative",
    "role": "Artist",
    "img": null
  },
  {
    "rank": 51,
    "zh": "乌尔班二世",
    "en": "Pope Urban II",
    "birth": 1042,
    "death": 1099,
    "birth_lat": 49,
    "birth_lng": 3,
    "region": "西欧",
    "countries": [
      "FR",
      "IT"
    ],
    "tags": [
      "role/Spirit/Religion/Clergy"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Clergy",
    "img": null
  },
  {
    "rank": 52,
    "zh": "欧麦尔一世",
    "en": "Umar Ibn Al-Khattab",
    "birth": 586,
    "death": 644,
    "birth_lat": 21.5,
    "birth_lng": 39.9,
    "region": "西亚",
    "countries": [
      "SA"
    ],
    "tags": [
      "role/Spirit/Religion/Clergy"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Clergy",
    "img": null
  },
  {
    "rank": 53,
    "zh": "阿育王",
    "en": "Asoka",
    "birth": -304,
    "death": -232,
    "birth_lat": 25.4,
    "birth_lng": 81.9,
    "region": "南亚",
    "countries": [
      "IN"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 54,
    "zh": "奥古斯丁",
    "en": "St. Augustine",
    "birth": 354,
    "death": 430,
    "birth_lat": 36.2,
    "birth_lng": 8.1,
    "region": "北非",
    "countries": [
      "DZ"
    ],
    "tags": [
      "role/Spirit/Religion/Theologian"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Theologian",
    "img": "https://docs.suphy.top/file/St_Augustine_1024.png"
  },
  {
    "rank": 55,
    "zh": "威廉·哈维",
    "en": "William Harvey",
    "birth": 1578,
    "death": 1657,
    "birth_lat": 51.1,
    "birth_lng": 1.2,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Doctor"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Doctor",
    "img": null
  },
  {
    "rank": 56,
    "zh": "欧内斯特·卢瑟福",
    "en": "Ernest Rutherford",
    "birth": 1871,
    "death": 1937,
    "birth_lat": -41.3,
    "birth_lng": 173.2,
    "region": "澳新",
    "countries": [
      "NZ",
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 57,
    "zh": "约翰·加尔文",
    "en": "John Calvin",
    "birth": 1509,
    "death": 1564,
    "birth_lat": 49.6,
    "birth_lng": 3,
    "region": "西欧",
    "countries": [
      "FR",
      "CH"
    ],
    "tags": [
      "role/Spirit/Religion/Theologian"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Theologian",
    "img": null
  },
  {
    "rank": 58,
    "zh": "孟德尔",
    "en": "Gregor Mendel",
    "birth": 1822,
    "death": 1884,
    "birth_lat": 49.7,
    "birth_lng": 17.9,
    "region": "东欧",
    "countries": [
      "CZ"
    ],
    "tags": [
      "role/Nature/Science/Biologist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Biologist",
    "img": null
  },
  {
    "rank": 59,
    "zh": "马克斯·普朗克",
    "en": "Max Planck",
    "birth": 1858,
    "death": 1947,
    "birth_lat": 54.3,
    "birth_lng": 10.1,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 60,
    "zh": "利斯特",
    "en": "Joseph Lister",
    "birth": 1827,
    "death": 1912,
    "birth_lat": 51.6,
    "birth_lng": 0.1,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Doctor"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Doctor",
    "img": null
  },
  {
    "rank": 61,
    "zh": "奥托",
    "en": "Nikolaus August Otto",
    "birth": 1832,
    "death": 1891,
    "birth_lat": 50.7,
    "birth_lng": 7.8,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Tech/Inventor"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Inventor",
    "img": null
  },
  {
    "rank": 62,
    "zh": "皮萨罗",
    "en": "Francisco Pizarro",
    "birth": 1475,
    "death": 1541,
    "birth_lat": 39.5,
    "birth_lng": -6.1,
    "region": "南欧",
    "countries": [
      "ES"
    ],
    "tags": [
      "role/Society/Frontier/Conqueror"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Conqueror",
    "img": null
  },
  {
    "rank": 63,
    "zh": "科尔特斯",
    "en": "Hernando Cortes",
    "birth": 1485,
    "death": 1547,
    "birth_lat": 38.9,
    "birth_lng": -6.2,
    "region": "南欧",
    "countries": [
      "ES"
    ],
    "tags": [
      "role/Society/Frontier/Conqueror"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Conqueror",
    "img": null
  },
  {
    "rank": 64,
    "zh": "托马斯·杰斐逊",
    "en": "Thomas Jefferson",
    "birth": 1743,
    "death": 1826,
    "birth_lat": 38,
    "birth_lng": -78.5,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 65,
    "zh": "伊莎贝拉一世",
    "en": "Queen Isabella I",
    "birth": 1451,
    "death": 1504,
    "birth_lat": 40.7,
    "birth_lng": -4.7,
    "region": "南欧",
    "countries": [
      "ES"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 66,
    "zh": "斯大林",
    "en": "Joseph Stalin",
    "birth": 1879,
    "death": 1953,
    "birth_lat": 41.9,
    "birth_lng": 44.1,
    "region": "东欧",
    "countries": [
      "RU"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 67,
    "zh": "凯撒",
    "en": "Julius Caesar",
    "birth": -100,
    "death": -44,
    "birth_lat": 41.9,
    "birth_lng": 12.5,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Society/Governance/General"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "General",
    "img": null
  },
  {
    "rank": 68,
    "zh": "征服者威廉",
    "en": "William the Conqueror",
    "birth": 1027,
    "death": 1087,
    "birth_lat": 48.9,
    "birth_lng": -0.2,
    "region": "北欧",
    "countries": [
      "GB",
      "FR"
    ],
    "tags": [
      "role/Society/Frontier/Conqueror"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Conqueror",
    "img": null
  },
  {
    "rank": 69,
    "zh": "弗洛伊德",
    "en": "Sigmund Freud",
    "birth": 1856,
    "death": 1939,
    "birth_lat": 49.7,
    "birth_lng": 18.2,
    "region": "西欧",
    "countries": [
      "AT",
      "CZ"
    ],
    "tags": [
      "role/Spirit/Humanities/SocialScientist"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "SocialScientist",
    "img": null
  },
  {
    "rank": 70,
    "zh": "爱德华·詹纳",
    "en": "Edward Jenner",
    "birth": 1749,
    "death": 1823,
    "birth_lat": 51.7,
    "birth_lng": -2.5,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Nature/Science/Doctor"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Doctor",
    "img": null
  },
  {
    "rank": 71,
    "zh": "伦琴",
    "en": "William Conrad Rontgen",
    "birth": 1845,
    "death": 1923,
    "birth_lat": 51.2,
    "birth_lng": 7.2,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 72,
    "zh": "巴赫",
    "en": "Johann Sebastian Bach",
    "birth": 1685,
    "death": 1750,
    "birth_lat": 51,
    "birth_lng": 10.3,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Spirit/Creative/Composer"
    ],
    "domain": "Spirit",
    "category": "Creative",
    "role": "Composer",
    "img": null
  },
  {
    "rank": 73,
    "zh": "老子",
    "en": "Lao Tzu",
    "birth": -600,
    "death": -500,
    "birth_lat": 34,
    "birth_lng": 114,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 74,
    "zh": "伏尔泰",
    "en": "Voltaire",
    "birth": 1694,
    "death": 1778,
    "birth_lat": 48.9,
    "birth_lng": 2.3,
    "region": "西欧",
    "countries": [
      "FR"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 75,
    "zh": "开普勒",
    "en": "Johannes Kepler",
    "birth": 1571,
    "death": 1630,
    "birth_lat": 48.8,
    "birth_lng": 8.9,
    "region": "西欧",
    "countries": [
      "DE"
    ],
    "tags": [
      "role/Nature/Science/Astronomer"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Astronomer",
    "img": null
  },
  {
    "rank": 76,
    "zh": "费米",
    "en": "Enrico Fermi",
    "birth": 1901,
    "death": 1954,
    "birth_lat": 41.9,
    "birth_lng": 12.5,
    "region": "南欧",
    "countries": [
      "IT",
      "US"
    ],
    "tags": [
      "role/Nature/Science/Physicist"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Physicist",
    "img": null
  },
  {
    "rank": 77,
    "zh": "欧拉",
    "en": "Leonhard Euler",
    "birth": 1707,
    "death": 1783,
    "birth_lat": 47.6,
    "birth_lng": 7.6,
    "region": "西欧",
    "countries": [
      "CH"
    ],
    "tags": [
      "role/Nature/Science/Mathematician"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "Mathematician",
    "img": null
  },
  {
    "rank": 78,
    "zh": "卢梭",
    "en": "Jean-Jacques Rousseau",
    "birth": 1712,
    "death": 1778,
    "birth_lat": 46.2,
    "birth_lng": 6.1,
    "region": "西欧",
    "countries": [
      "FR",
      "CH"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 79,
    "zh": "马基雅维利",
    "en": "Niccolo Machiavelli",
    "birth": 1469,
    "death": 1527,
    "birth_lat": 43.8,
    "birth_lng": 11.2,
    "region": "南欧",
    "countries": [
      "IT"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 80,
    "zh": "马尔萨斯",
    "en": "Thomas Malthus",
    "birth": 1766,
    "death": 1834,
    "birth_lat": 51.2,
    "birth_lng": -0.3,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Spirit/Humanities/SocialScientist"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "SocialScientist",
    "img": null
  },
  {
    "rank": 81,
    "zh": "约翰·肯尼迪",
    "en": "John F. Kennedy",
    "birth": 1917,
    "death": 1963,
    "birth_lat": 42.3,
    "birth_lng": -71.1,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 82,
    "zh": "平卡斯",
    "en": "Gregory Pincus",
    "birth": 1903,
    "death": 1967,
    "birth_lat": 40.7,
    "birth_lng": -74,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Nature/Science/MedResearcher"
    ],
    "domain": "Nature",
    "category": "Science",
    "role": "MedResearcher",
    "img": null
  },
  {
    "rank": 83,
    "zh": "摩尼",
    "en": "Mani",
    "birth": 216,
    "death": 276,
    "birth_lat": 32.5,
    "birth_lng": 44.5,
    "region": "西亚",
    "countries": [
      "IR"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  },
  {
    "rank": 84,
    "zh": "列宁",
    "en": "Lenin",
    "birth": 1870,
    "death": 1924,
    "birth_lat": 54.3,
    "birth_lng": 48.4,
    "region": "东欧",
    "countries": [
      "RU"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 85,
    "zh": "隋文帝",
    "en": "Sui Wen Ti",
    "birth": 541,
    "death": 604,
    "birth_lat": 34.3,
    "birth_lng": 108.9,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 86,
    "zh": "达·伽马",
    "en": "Vasco da Gama",
    "birth": 1460,
    "death": 1524,
    "birth_lat": 37.9,
    "birth_lng": -8.9,
    "region": "南欧",
    "countries": [
      "PT"
    ],
    "tags": [
      "role/Society/Frontier/Explorer"
    ],
    "domain": "Society",
    "category": "Frontier",
    "role": "Explorer",
    "img": null
  },
  {
    "rank": 87,
    "zh": "居鲁士大帝",
    "en": "Cyrus the Great",
    "birth": -590,
    "death": -529,
    "birth_lat": 30.2,
    "birth_lng": 52,
    "region": "西亚",
    "countries": [
      "IR"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 88,
    "zh": "彼得大帝",
    "en": "Peter the Great",
    "birth": 1672,
    "death": 1725,
    "birth_lat": 55.8,
    "birth_lng": 37.6,
    "region": "东欧",
    "countries": [
      "RU"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 89,
    "zh": "毛泽东",
    "en": "Mao Zedong",
    "birth": 1893,
    "death": 1976,
    "birth_lat": 27.9,
    "birth_lng": 112.5,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 90,
    "zh": "弗朗西斯·培根",
    "en": "Francis Bacon",
    "birth": 1561,
    "death": 1626,
    "birth_lat": 51.5,
    "birth_lng": -0.1,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 91,
    "zh": "福特",
    "en": "Henry Ford",
    "birth": 1863,
    "death": 1947,
    "birth_lat": 42.3,
    "birth_lng": -83.2,
    "region": "北美洲",
    "countries": [
      "US"
    ],
    "tags": [
      "role/Nature/Tech/Industrialist"
    ],
    "domain": "Nature",
    "category": "Tech",
    "role": "Industrialist",
    "img": null
  },
  {
    "rank": 92,
    "zh": "孟子",
    "en": "Mencius",
    "birth": -371,
    "death": -289,
    "birth_lat": 35.4,
    "birth_lng": 117.1,
    "region": "东亚",
    "countries": [
      "CN"
    ],
    "tags": [
      "role/Spirit/Humanities/Philosopher"
    ],
    "domain": "Spirit",
    "category": "Humanities",
    "role": "Philosopher",
    "img": null
  },
  {
    "rank": 93,
    "zh": "琐罗亚斯德",
    "en": "Zoroaster",
    "birth": -628,
    "death": -551,
    "birth_lat": 35.7,
    "birth_lng": 51.4,
    "region": "西亚",
    "countries": [
      "IR"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  },
  {
    "rank": 94,
    "zh": "伊丽莎白一世",
    "en": "Queen Elizabeth I",
    "birth": 1533,
    "death": 1603,
    "birth_lat": 51.5,
    "birth_lng": 0,
    "region": "北欧",
    "countries": [
      "GB"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 95,
    "zh": "戈尔巴乔夫",
    "en": "Mikhail Gorbachev",
    "birth": 1931,
    "death": 2022,
    "birth_lat": 45.1,
    "birth_lng": 41.9,
    "region": "东欧",
    "countries": [
      "RU"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 96,
    "zh": "美尼斯",
    "en": "Menes",
    "birth": -3100,
    "death": -3050,
    "birth_lat": 26,
    "birth_lng": 32.5,
    "region": "北非",
    "countries": [
      "EG"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 97,
    "zh": "查理曼",
    "en": "Charlemagne",
    "birth": 742,
    "death": 814,
    "birth_lat": 50.6,
    "birth_lng": 5.6,
    "region": "西欧",
    "countries": [
      "FR",
      "DE"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 98,
    "zh": "荷马",
    "en": "Homer",
    "birth": -800,
    "death": -750,
    "birth_lat": 38.5,
    "birth_lng": 27,
    "region": "南欧",
    "countries": [
      "GR"
    ],
    "tags": [
      "role/Spirit/Creative/Author"
    ],
    "domain": "Spirit",
    "category": "Creative",
    "role": "Author",
    "img": null
  },
  {
    "rank": 99,
    "zh": "查士丁尼一世",
    "en": "Justinian I",
    "birth": 483,
    "death": 565,
    "birth_lat": 41.9,
    "birth_lng": 22.4,
    "region": "西亚",
    "countries": [
      "TR"
    ],
    "tags": [
      "role/Society/Governance/Politician"
    ],
    "domain": "Society",
    "category": "Governance",
    "role": "Politician",
    "img": null
  },
  {
    "rank": 100,
    "zh": "摩诃毗罗",
    "en": "Mahavira",
    "birth": -599,
    "death": -527,
    "birth_lat": 25.1,
    "birth_lng": 85.5,
    "region": "南亚",
    "countries": [
      "IN"
    ],
    "tags": [
      "role/Spirit/Religion/Spiritual"
    ],
    "domain": "Spirit",
    "category": "Religion",
    "role": "Spiritual",
    "img": null
  }
];

// Countries keyed by ISO code — _region/ notes merged with country-ref.js (complete)
const COUNTRIES = {
  "AT": {
    "zh": "奥地利",
    "en": "Austria",
    "lat": 47.5,
    "lon": 14.6,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/at.png"
  },
  "CH": {
    "zh": "瑞士",
    "en": "Switzerland",
    "lat": 46.8,
    "lon": 8.2,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ch.png"
  },
  "CN": {
    "zh": "中国",
    "en": "China",
    "lat": 35.9,
    "lon": 104.2,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/cn.png"
  },
  "CZ": {
    "zh": "捷克",
    "en": "Czech Republic",
    "lat": 49.8,
    "lon": 15.5,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/cz.png"
  },
  "DE": {
    "zh": "德国",
    "en": "Germany",
    "lat": 51.2,
    "lon": 10.5,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/de.png"
  },
  "DZ": {
    "zh": "阿尔及利亚",
    "en": "Algeria",
    "lat": 28,
    "lon": 1.7,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/dz.png"
  },
  "EG": {
    "zh": "埃及",
    "en": "Egypt",
    "lat": 26.8,
    "lon": 30.8,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/eg.png"
  },
  "ES": {
    "zh": "西班牙",
    "en": "Spain",
    "lat": 40.5,
    "lon": -3.7,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/es.png"
  },
  "FR": {
    "zh": "法国",
    "en": "France",
    "lat": 46.2,
    "lon": 2.2,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/fr.png"
  },
  "GB": {
    "zh": "英国",
    "en": "United Kingdom",
    "lat": 55.4,
    "lon": -3.4,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/gb.png"
  },
  "GR": {
    "zh": "希腊",
    "en": "Greece",
    "lat": 39.1,
    "lon": 21.8,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/gr.png"
  },
  "IN": {
    "zh": "印度",
    "en": "India",
    "lat": 20.6,
    "lon": 78.9,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/in.png"
  },
  "IR": {
    "zh": "伊朗",
    "en": "Iran",
    "lat": 32.4,
    "lon": 53.7,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ir.png"
  },
  "IT": {
    "zh": "意大利",
    "en": "Italy",
    "lat": 41.9,
    "lon": 12.6,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/it.png"
  },
  "MN": {
    "zh": "蒙古",
    "en": "Mongolia",
    "lat": 46.9,
    "lon": 103.8,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/mn.png"
  },
  "NL": {
    "zh": "荷兰",
    "en": "Netherlands",
    "lat": 52.1,
    "lon": 5.3,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/nl.png"
  },
  "NP": {
    "zh": "尼泊尔",
    "en": "Nepal",
    "lat": 28.4,
    "lon": 84.1,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/np.png"
  },
  "NZ": {
    "zh": "新西兰",
    "en": "New Zealand",
    "lat": -40.9,
    "lon": 174.9,
    "subregion": "澳新",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/nz.png"
  },
  "PL": {
    "zh": "波兰",
    "en": "Poland",
    "lat": 51.9,
    "lon": 19.1,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/pl.png"
  },
  "PS": {
    "zh": "巴勒斯坦",
    "en": "Palestine",
    "lat": 31.9,
    "lon": 35.2,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ps.png"
  },
  "PT": {
    "zh": "葡萄牙",
    "en": "Portugal",
    "lat": 39.4,
    "lon": -8.2,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/pt.png"
  },
  "RS": {
    "zh": "塞尔维亚",
    "en": "Serbia",
    "lat": 44,
    "lon": 21,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/rs.png"
  },
  "RU": {
    "zh": "俄罗斯",
    "en": "Russia",
    "lat": 61.5,
    "lon": 105.3,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ru.png"
  },
  "SA": {
    "zh": "沙特阿拉伯",
    "en": "Saudi Arabia",
    "lat": 23.9,
    "lon": 45.1,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/sa.png"
  },
  "TR": {
    "zh": "土耳其",
    "en": "Turkey",
    "lat": 39,
    "lon": 35.2,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/tr.png"
  },
  "US": {
    "zh": "美国",
    "en": "United States",
    "lat": 37.1,
    "lon": -95.7,
    "subregion": "",
    "continent": "北美洲",
    "flag": "https://flagcdn.com/w320/us.png"
  },
  "VE": {
    "zh": "委内瑞拉",
    "en": "Venezuela",
    "lat": 6.4,
    "lon": -66.6,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ve.png"
  },
  "JP": {
    "zh": "日本",
    "en": "Japan",
    "lat": 36.2,
    "lon": 138.3,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/jp.png"
  },
  "KP": {
    "zh": "朝鲜",
    "en": "North Korea",
    "lat": 40.3,
    "lon": 127.5,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kp.png"
  },
  "KR": {
    "zh": "韩国",
    "en": "South Korea",
    "lat": 36.5,
    "lon": 127.8,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kr.png"
  },
  "TW": {
    "zh": "台湾",
    "en": "Taiwan",
    "lat": 23.7,
    "lon": 121,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/tw.png"
  },
  "HK": {
    "zh": "香港",
    "en": "Hong Kong",
    "lat": 22.3,
    "lon": 114.2,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/hk.png"
  },
  "MO": {
    "zh": "澳门",
    "en": "Macau",
    "lat": 22.2,
    "lon": 113.5,
    "subregion": "东亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/mo.png"
  },
  "MM": {
    "zh": "缅甸",
    "en": "Myanmar",
    "lat": 21.9,
    "lon": 96,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/mm.png"
  },
  "KH": {
    "zh": "柬埔寨",
    "en": "Cambodia",
    "lat": 12.6,
    "lon": 104.9,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kh.png"
  },
  "ID": {
    "zh": "印度尼西亚",
    "en": "Indonesia",
    "lat": -2.5,
    "lon": 118,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/id.png"
  },
  "LA": {
    "zh": "老挝",
    "en": "Laos",
    "lat": 19.9,
    "lon": 102.5,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/la.png"
  },
  "MY": {
    "zh": "马来西亚",
    "en": "Malaysia",
    "lat": 4.2,
    "lon": 102,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/my.png"
  },
  "PH": {
    "zh": "菲律宾",
    "en": "Philippines",
    "lat": 12.9,
    "lon": 121.8,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ph.png"
  },
  "SG": {
    "zh": "新加坡",
    "en": "Singapore",
    "lat": 1.35,
    "lon": 103.8,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/sg.png"
  },
  "TH": {
    "zh": "泰国",
    "en": "Thailand",
    "lat": 15,
    "lon": 101,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/th.png"
  },
  "VN": {
    "zh": "越南",
    "en": "Vietnam",
    "lat": 16,
    "lon": 107.8,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/vn.png"
  },
  "BN": {
    "zh": "文莱",
    "en": "Brunei",
    "lat": 4.5,
    "lon": 114.7,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/bn.png"
  },
  "TL": {
    "zh": "东帝汶",
    "en": "Timor-Leste",
    "lat": -8.8,
    "lon": 125.7,
    "subregion": "东南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/tl.png"
  },
  "AF": {
    "zh": "阿富汗",
    "en": "Afghanistan",
    "lat": 33.9,
    "lon": 67.7,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/af.png"
  },
  "BD": {
    "zh": "孟加拉国",
    "en": "Bangladesh",
    "lat": 23.7,
    "lon": 90.4,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/bd.png"
  },
  "BT": {
    "zh": "不丹",
    "en": "Bhutan",
    "lat": 27.5,
    "lon": 90.4,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/bt.png"
  },
  "LK": {
    "zh": "斯里兰卡",
    "en": "Sri Lanka",
    "lat": 7.9,
    "lon": 80.7,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/lk.png"
  },
  "MV": {
    "zh": "马尔代夫",
    "en": "Maldives",
    "lat": 3.2,
    "lon": 73.2,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/mv.png"
  },
  "PK": {
    "zh": "巴基斯坦",
    "en": "Pakistan",
    "lat": 30.4,
    "lon": 69.3,
    "subregion": "南亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/pk.png"
  },
  "KZ": {
    "zh": "哈萨克斯坦",
    "en": "Kazakhstan",
    "lat": 48,
    "lon": 67,
    "subregion": "中亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kz.png"
  },
  "KG": {
    "zh": "吉尔吉斯斯坦",
    "en": "Kyrgyzstan",
    "lat": 41.2,
    "lon": 74.8,
    "subregion": "中亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kg.png"
  },
  "TJ": {
    "zh": "塔吉克斯坦",
    "en": "Tajikistan",
    "lat": 38.9,
    "lon": 71.3,
    "subregion": "中亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/tj.png"
  },
  "TM": {
    "zh": "土库曼斯坦",
    "en": "Turkmenistan",
    "lat": 39.1,
    "lon": 59.4,
    "subregion": "中亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/tm.png"
  },
  "UZ": {
    "zh": "乌兹别克斯坦",
    "en": "Uzbekistan",
    "lat": 41.4,
    "lon": 64.6,
    "subregion": "中亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/uz.png"
  },
  "AM": {
    "zh": "亚美尼亚",
    "en": "Armenia",
    "lat": 40.1,
    "lon": 45,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/am.png"
  },
  "AZ": {
    "zh": "阿塞拜疆",
    "en": "Azerbaijan",
    "lat": 40.4,
    "lon": 47.6,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/az.png"
  },
  "BH": {
    "zh": "巴林",
    "en": "Bahrain",
    "lat": 26,
    "lon": 50.55,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/bh.png"
  },
  "CY": {
    "zh": "塞浦路斯",
    "en": "Cyprus",
    "lat": 35.1,
    "lon": 33.4,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/cy.png"
  },
  "GE": {
    "zh": "格鲁吉亚",
    "en": "Georgia",
    "lat": 42.3,
    "lon": 43.4,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ge.png"
  },
  "IQ": {
    "zh": "伊拉克",
    "en": "Iraq",
    "lat": 33.2,
    "lon": 43.7,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/iq.png"
  },
  "IL": {
    "zh": "以色列",
    "en": "Israel",
    "lat": 31.5,
    "lon": 34.9,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/il.png"
  },
  "JO": {
    "zh": "约旦",
    "en": "Jordan",
    "lat": 31.2,
    "lon": 36.8,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/jo.png"
  },
  "KW": {
    "zh": "科威特",
    "en": "Kuwait",
    "lat": 29.3,
    "lon": 47.5,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/kw.png"
  },
  "LB": {
    "zh": "黎巴嫩",
    "en": "Lebanon",
    "lat": 33.9,
    "lon": 35.9,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/lb.png"
  },
  "OM": {
    "zh": "阿曼",
    "en": "Oman",
    "lat": 21.5,
    "lon": 55.9,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/om.png"
  },
  "QA": {
    "zh": "卡塔尔",
    "en": "Qatar",
    "lat": 25.3,
    "lon": 51.2,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/qa.png"
  },
  "SY": {
    "zh": "叙利亚",
    "en": "Syria",
    "lat": 35,
    "lon": 38.5,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/sy.png"
  },
  "AE": {
    "zh": "阿拉伯联合酋长国",
    "en": "United Arab Emirates",
    "lat": 23.9,
    "lon": 54.3,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ae.png"
  },
  "YE": {
    "zh": "也门",
    "en": "Yemen",
    "lat": 15.5,
    "lon": 48,
    "subregion": "西亚",
    "continent": "亚洲",
    "flag": "https://flagcdn.com/w320/ye.png"
  },
  "DK": {
    "zh": "丹麦",
    "en": "Denmark",
    "lat": 56,
    "lon": 10,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/dk.png"
  },
  "EE": {
    "zh": "爱沙尼亚",
    "en": "Estonia",
    "lat": 58.7,
    "lon": 25.5,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ee.png"
  },
  "FI": {
    "zh": "芬兰",
    "en": "Finland",
    "lat": 64.5,
    "lon": 26,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/fi.png"
  },
  "IS": {
    "zh": "冰岛",
    "en": "Iceland",
    "lat": 64.9,
    "lon": -18.6,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/is.png"
  },
  "IE": {
    "zh": "爱尔兰",
    "en": "Ireland",
    "lat": 53.2,
    "lon": -8,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ie.png"
  },
  "LV": {
    "zh": "拉脱维亚",
    "en": "Latvia",
    "lat": 56.9,
    "lon": 24.9,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/lv.png"
  },
  "LT": {
    "zh": "立陶宛",
    "en": "Lithuania",
    "lat": 55.2,
    "lon": 23.9,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/lt.png"
  },
  "NO": {
    "zh": "挪威",
    "en": "Norway",
    "lat": 64.5,
    "lon": 12,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/no.png"
  },
  "SE": {
    "zh": "瑞典",
    "en": "Sweden",
    "lat": 62,
    "lon": 15,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/se.png"
  },
  "FO": {
    "zh": "法罗群岛",
    "en": "Faroe Islands",
    "lat": 62,
    "lon": -6.9,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/fo.png"
  },
  "AX": {
    "zh": "奥兰群岛",
    "en": "Åland Islands",
    "lat": 60.2,
    "lon": 20,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ax.png"
  },
  "GG": {
    "zh": "根西",
    "en": "Guernsey",
    "lat": 49.45,
    "lon": -2.58,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/gg.png"
  },
  "JE": {
    "zh": "泽西",
    "en": "Jersey",
    "lat": 49.2,
    "lon": -2.13,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/je.png"
  },
  "IM": {
    "zh": "马恩岛",
    "en": "Isle of Man",
    "lat": 54.2,
    "lon": -4.5,
    "subregion": "北欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/im.png"
  },
  "BE": {
    "zh": "比利时",
    "en": "Belgium",
    "lat": 50.6,
    "lon": 4.6,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/be.png"
  },
  "LI": {
    "zh": "列支敦士登",
    "en": "Liechtenstein",
    "lat": 47.2,
    "lon": 9.55,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/li.png"
  },
  "LU": {
    "zh": "卢森堡",
    "en": "Luxembourg",
    "lat": 49.8,
    "lon": 6.1,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/lu.png"
  },
  "MC": {
    "zh": "摩纳哥",
    "en": "Monaco",
    "lat": 43.74,
    "lon": 7.42,
    "subregion": "西欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/mc.png"
  },
  "BY": {
    "zh": "白俄罗斯",
    "en": "Belarus",
    "lat": 53.7,
    "lon": 28,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/by.png"
  },
  "BG": {
    "zh": "保加利亚",
    "en": "Bulgaria",
    "lat": 42.7,
    "lon": 25.2,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/bg.png"
  },
  "HU": {
    "zh": "匈牙利",
    "en": "Hungary",
    "lat": 47.2,
    "lon": 19.4,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/hu.png"
  },
  "MD": {
    "zh": "摩尔多瓦",
    "en": "Moldova",
    "lat": 47.2,
    "lon": 28.5,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/md.png"
  },
  "RO": {
    "zh": "罗马尼亚",
    "en": "Romania",
    "lat": 45.9,
    "lon": 25,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ro.png"
  },
  "SK": {
    "zh": "斯洛伐克",
    "en": "Slovakia",
    "lat": 48.7,
    "lon": 19.7,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/sk.png"
  },
  "UA": {
    "zh": "乌克兰",
    "en": "Ukraine",
    "lat": 49,
    "lon": 31.4,
    "subregion": "东欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ua.png"
  },
  "AL": {
    "zh": "阿尔巴尼亚",
    "en": "Albania",
    "lat": 41.2,
    "lon": 20,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/al.png"
  },
  "AD": {
    "zh": "安道尔",
    "en": "Andorra",
    "lat": 42.5,
    "lon": 1.5,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ad.png"
  },
  "BA": {
    "zh": "波斯尼亚和黑塞哥维那",
    "en": "Bosnia and Herzegovina",
    "lat": 44,
    "lon": 18,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/ba.png"
  },
  "HR": {
    "zh": "克罗地亚",
    "en": "Croatia",
    "lat": 45.2,
    "lon": 15.5,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/hr.png"
  },
  "GI": {
    "zh": "直布罗陀",
    "en": "Gibraltar",
    "lat": 36.14,
    "lon": -5.35,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/gi.png"
  },
  "MT": {
    "zh": "马耳他",
    "en": "Malta",
    "lat": 35.9,
    "lon": 14.4,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/mt.png"
  },
  "ME": {
    "zh": "黑山",
    "en": "Montenegro",
    "lat": 42.7,
    "lon": 19.4,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/me.png"
  },
  "MK": {
    "zh": "北马其顿",
    "en": "North Macedonia",
    "lat": 41.6,
    "lon": 21.7,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/mk.png"
  },
  "SI": {
    "zh": "斯洛文尼亚",
    "en": "Slovenia",
    "lat": 46.1,
    "lon": 14.8,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/si.png"
  },
  "VA": {
    "zh": "梵蒂冈",
    "en": "Vatican City",
    "lat": 41.9,
    "lon": 12.45,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/va.png"
  },
  "SM": {
    "zh": "圣马力诺",
    "en": "San Marino",
    "lat": 43.94,
    "lon": 12.46,
    "subregion": "南欧",
    "continent": "欧洲",
    "flag": "https://flagcdn.com/w320/sm.png"
  },
  "LY": {
    "zh": "利比亚",
    "en": "Libya",
    "lat": 27,
    "lon": 18,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ly.png"
  },
  "MA": {
    "zh": "摩洛哥",
    "en": "Morocco",
    "lat": 31.8,
    "lon": -7,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ma.png"
  },
  "SD": {
    "zh": "苏丹",
    "en": "Sudan",
    "lat": 15.5,
    "lon": 30.2,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sd.png"
  },
  "TN": {
    "zh": "突尼斯",
    "en": "Tunisia",
    "lat": 34,
    "lon": 9.5,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/tn.png"
  },
  "EH": {
    "zh": "西撒哈拉",
    "en": "Western Sahara",
    "lat": 24.5,
    "lon": -13,
    "subregion": "北非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/eh.png"
  },
  "BJ": {
    "zh": "贝宁",
    "en": "Benin",
    "lat": 9.6,
    "lon": 2.3,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/bj.png"
  },
  "BF": {
    "zh": "布基纳法索",
    "en": "Burkina Faso",
    "lat": 12.2,
    "lon": -1.6,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/bf.png"
  },
  "CV": {
    "zh": "佛得角",
    "en": "Cape Verde",
    "lat": 16,
    "lon": -24,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/cv.png"
  },
  "CI": {
    "zh": "科特迪瓦",
    "en": "Côte d'Ivoire",
    "lat": 7.6,
    "lon": -5.5,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ci.png"
  },
  "GM": {
    "zh": "冈比亚",
    "en": "Gambia",
    "lat": 13.4,
    "lon": -15.4,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/gm.png"
  },
  "GH": {
    "zh": "加纳",
    "en": "Ghana",
    "lat": 7.9,
    "lon": -1,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/gh.png"
  },
  "GN": {
    "zh": "几内亚",
    "en": "Guinea",
    "lat": 10.4,
    "lon": -10.9,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/gn.png"
  },
  "GW": {
    "zh": "几内亚比绍",
    "en": "Guinea-Bissau",
    "lat": 12,
    "lon": -15,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/gw.png"
  },
  "LR": {
    "zh": "利比里亚",
    "en": "Liberia",
    "lat": 6.4,
    "lon": -9.4,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/lr.png"
  },
  "ML": {
    "zh": "马里",
    "en": "Mali",
    "lat": 17.6,
    "lon": -4,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ml.png"
  },
  "MR": {
    "zh": "毛里塔尼亚",
    "en": "Mauritania",
    "lat": 20.3,
    "lon": -10.3,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/mr.png"
  },
  "NE": {
    "zh": "尼日尔",
    "en": "Niger",
    "lat": 17.6,
    "lon": 8.1,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ne.png"
  },
  "NG": {
    "zh": "尼日利亚",
    "en": "Nigeria",
    "lat": 9.1,
    "lon": 8.7,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ng.png"
  },
  "SN": {
    "zh": "塞内加尔",
    "en": "Senegal",
    "lat": 14.5,
    "lon": -14.5,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sn.png"
  },
  "SL": {
    "zh": "塞拉利昂",
    "en": "Sierra Leone",
    "lat": 8.5,
    "lon": -11.8,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sl.png"
  },
  "TG": {
    "zh": "多哥",
    "en": "Togo",
    "lat": 8.6,
    "lon": 0.8,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/tg.png"
  },
  "SH": {
    "zh": "圣赫勒拿",
    "en": "Saint Helena",
    "lat": -15.95,
    "lon": -5.7,
    "subregion": "西非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sh.png"
  },
  "AO": {
    "zh": "安哥拉",
    "en": "Angola",
    "lat": -11.2,
    "lon": 17.9,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ao.png"
  },
  "CM": {
    "zh": "喀麦隆",
    "en": "Cameroon",
    "lat": 5.7,
    "lon": 12.7,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/cm.png"
  },
  "CF": {
    "zh": "中非共和国",
    "en": "Central African Republic",
    "lat": 6.6,
    "lon": 20.9,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/cf.png"
  },
  "TD": {
    "zh": "乍得",
    "en": "Chad",
    "lat": 15.4,
    "lon": 18.7,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/td.png"
  },
  "CG": {
    "zh": "刚果（布）",
    "en": "Republic of the Congo",
    "lat": -0.8,
    "lon": 15.2,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/cg.png"
  },
  "CD": {
    "zh": "刚果（金）",
    "en": "DR Congo",
    "lat": -2.9,
    "lon": 23.6,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/cd.png"
  },
  "GQ": {
    "zh": "赤道几内亚",
    "en": "Equatorial Guinea",
    "lat": 1.6,
    "lon": 10.3,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/gq.png"
  },
  "GA": {
    "zh": "加蓬",
    "en": "Gabon",
    "lat": -0.6,
    "lon": 11.8,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ga.png"
  },
  "ST": {
    "zh": "圣多美和普林西比",
    "en": "São Tomé and Príncipe",
    "lat": 0.2,
    "lon": 6.6,
    "subregion": "中非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/st.png"
  },
  "BI": {
    "zh": "布隆迪",
    "en": "Burundi",
    "lat": -3.4,
    "lon": 29.9,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/bi.png"
  },
  "KM": {
    "zh": "科摩罗",
    "en": "Comoros",
    "lat": -11.6,
    "lon": 43.3,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/km.png"
  },
  "DJ": {
    "zh": "吉布提",
    "en": "Djibouti",
    "lat": 11.8,
    "lon": 42.6,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/dj.png"
  },
  "ER": {
    "zh": "厄立特里亚",
    "en": "Eritrea",
    "lat": 15.2,
    "lon": 39.8,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/er.png"
  },
  "ET": {
    "zh": "埃塞俄比亚",
    "en": "Ethiopia",
    "lat": 9.1,
    "lon": 40.5,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/et.png"
  },
  "KE": {
    "zh": "肯尼亚",
    "en": "Kenya",
    "lat": 0.2,
    "lon": 37.9,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ke.png"
  },
  "MG": {
    "zh": "马达加斯加",
    "en": "Madagascar",
    "lat": -19,
    "lon": 46.7,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/mg.png"
  },
  "MW": {
    "zh": "马拉维",
    "en": "Malawi",
    "lat": -13.3,
    "lon": 34.3,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/mw.png"
  },
  "MU": {
    "zh": "毛里求斯",
    "en": "Mauritius",
    "lat": -20.3,
    "lon": 57.6,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/mu.png"
  },
  "YT": {
    "zh": "马约特",
    "en": "Mayotte",
    "lat": -12.8,
    "lon": 45.2,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/yt.png"
  },
  "MZ": {
    "zh": "莫桑比克",
    "en": "Mozambique",
    "lat": -18.3,
    "lon": 35.5,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/mz.png"
  },
  "RE": {
    "zh": "留尼汪",
    "en": "Réunion",
    "lat": -21.1,
    "lon": 55.5,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/re.png"
  },
  "RW": {
    "zh": "卢旺达",
    "en": "Rwanda",
    "lat": -1.9,
    "lon": 29.9,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/rw.png"
  },
  "SC": {
    "zh": "塞舌尔",
    "en": "Seychelles",
    "lat": -4.7,
    "lon": 55.5,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sc.png"
  },
  "SO": {
    "zh": "索马里",
    "en": "Somalia",
    "lat": 5.2,
    "lon": 46.2,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/so.png"
  },
  "SS": {
    "zh": "南苏丹",
    "en": "South Sudan",
    "lat": 7.3,
    "lon": 30.3,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ss.png"
  },
  "TZ": {
    "zh": "坦桑尼亚",
    "en": "Tanzania",
    "lat": -6.4,
    "lon": 35,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/tz.png"
  },
  "UG": {
    "zh": "乌干达",
    "en": "Uganda",
    "lat": 1.4,
    "lon": 32.4,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ug.png"
  },
  "ZM": {
    "zh": "赞比亚",
    "en": "Zambia",
    "lat": -13.1,
    "lon": 27.8,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/zm.png"
  },
  "ZW": {
    "zh": "津巴布韦",
    "en": "Zimbabwe",
    "lat": -19,
    "lon": 29.8,
    "subregion": "东非",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/zw.png"
  },
  "BW": {
    "zh": "博茨瓦纳",
    "en": "Botswana",
    "lat": -22.3,
    "lon": 24.7,
    "subregion": "南部非洲",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/bw.png"
  },
  "LS": {
    "zh": "莱索托",
    "en": "Lesotho",
    "lat": -29.6,
    "lon": 28.2,
    "subregion": "南部非洲",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/ls.png"
  },
  "NA": {
    "zh": "纳米比亚",
    "en": "Namibia",
    "lat": -22,
    "lon": 17.2,
    "subregion": "南部非洲",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/na.png"
  },
  "ZA": {
    "zh": "南非",
    "en": "South Africa",
    "lat": -29,
    "lon": 24,
    "subregion": "南部非洲",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/za.png"
  },
  "SZ": {
    "zh": "斯威士兰",
    "en": "Eswatini",
    "lat": -26.5,
    "lon": 31.5,
    "subregion": "南部非洲",
    "continent": "非洲",
    "flag": "https://flagcdn.com/w320/sz.png"
  },
  "BZ": {
    "zh": "伯利兹",
    "en": "Belize",
    "lat": 17.2,
    "lon": -88.5,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/bz.png"
  },
  "CR": {
    "zh": "哥斯达黎加",
    "en": "Costa Rica",
    "lat": 9.9,
    "lon": -84.1,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/cr.png"
  },
  "SV": {
    "zh": "萨尔瓦多",
    "en": "El Salvador",
    "lat": 13.8,
    "lon": -88.9,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/sv.png"
  },
  "GT": {
    "zh": "危地马拉",
    "en": "Guatemala",
    "lat": 15.7,
    "lon": -90.3,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gt.png"
  },
  "HN": {
    "zh": "洪都拉斯",
    "en": "Honduras",
    "lat": 14.8,
    "lon": -86.6,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/hn.png"
  },
  "MX": {
    "zh": "墨西哥",
    "en": "Mexico",
    "lat": 23.6,
    "lon": -102.5,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/mx.png"
  },
  "NI": {
    "zh": "尼加拉瓜",
    "en": "Nicaragua",
    "lat": 12.9,
    "lon": -85.2,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ni.png"
  },
  "PA": {
    "zh": "巴拿马",
    "en": "Panama",
    "lat": 8.5,
    "lon": -80.1,
    "subregion": "中美洲",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/pa.png"
  },
  "AG": {
    "zh": "安提瓜和巴布达",
    "en": "Antigua and Barbuda",
    "lat": 17.1,
    "lon": -61.8,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ag.png"
  },
  "AI": {
    "zh": "安圭拉",
    "en": "Anguilla",
    "lat": 18.2,
    "lon": -63.1,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ai.png"
  },
  "AW": {
    "zh": "阿鲁巴",
    "en": "Aruba",
    "lat": 12.5,
    "lon": -69.97,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/aw.png"
  },
  "BS": {
    "zh": "巴哈马",
    "en": "Bahamas",
    "lat": 25,
    "lon": -77.4,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/bs.png"
  },
  "BB": {
    "zh": "巴巴多斯",
    "en": "Barbados",
    "lat": 13.2,
    "lon": -59.5,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/bb.png"
  },
  "BQ": {
    "zh": "博奈尔",
    "en": "Bonaire",
    "lat": 12.2,
    "lon": -68.3,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/bq.png"
  },
  "CU": {
    "zh": "古巴",
    "en": "Cuba",
    "lat": 21.5,
    "lon": -79.5,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/cu.png"
  },
  "CW": {
    "zh": "库拉索",
    "en": "Curaçao",
    "lat": 12.2,
    "lon": -69,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/cw.png"
  },
  "DM": {
    "zh": "多米尼克",
    "en": "Dominica",
    "lat": 15.4,
    "lon": -61.4,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/dm.png"
  },
  "DO": {
    "zh": "多米尼加",
    "en": "Dominican Republic",
    "lat": 18.7,
    "lon": -70.2,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/do.png"
  },
  "GD": {
    "zh": "格林纳达",
    "en": "Grenada",
    "lat": 12.1,
    "lon": -61.7,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gd.png"
  },
  "GP": {
    "zh": "瓜德罗普",
    "en": "Guadeloupe",
    "lat": 16.2,
    "lon": -61.6,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gp.png"
  },
  "HT": {
    "zh": "海地",
    "en": "Haiti",
    "lat": 19,
    "lon": -72.3,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ht.png"
  },
  "JM": {
    "zh": "牙买加",
    "en": "Jamaica",
    "lat": 18.1,
    "lon": -77.3,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/jm.png"
  },
  "KN": {
    "zh": "圣基茨和尼维斯",
    "en": "Saint Kitts and Nevis",
    "lat": 17.3,
    "lon": -62.7,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/kn.png"
  },
  "LC": {
    "zh": "圣卢西亚",
    "en": "Saint Lucia",
    "lat": 13.9,
    "lon": -61,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/lc.png"
  },
  "MF": {
    "zh": "法属圣马丁",
    "en": "Saint Martin",
    "lat": 18.08,
    "lon": -63.05,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/mf.png"
  },
  "MQ": {
    "zh": "马提尼克",
    "en": "Martinique",
    "lat": 14.6,
    "lon": -61,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/mq.png"
  },
  "MS": {
    "zh": "蒙特塞拉特",
    "en": "Montserrat",
    "lat": 16.7,
    "lon": -62.2,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ms.png"
  },
  "PR": {
    "zh": "波多黎各",
    "en": "Puerto Rico",
    "lat": 18.2,
    "lon": -66.5,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/pr.png"
  },
  "SX": {
    "zh": "荷属圣马丁",
    "en": "Sint Maarten",
    "lat": 18.04,
    "lon": -63.06,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/sx.png"
  },
  "TT": {
    "zh": "特立尼达和多巴哥",
    "en": "Trinidad and Tobago",
    "lat": 10.7,
    "lon": -61.2,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/tt.png"
  },
  "VC": {
    "zh": "圣文森特和格林纳丁斯",
    "en": "Saint Vincent and the Grenadines",
    "lat": 13,
    "lon": -61.2,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/vc.png"
  },
  "VI": {
    "zh": "美属维尔京群岛",
    "en": "U.S. Virgin Islands",
    "lat": 18.3,
    "lon": -64.9,
    "subregion": "加勒比",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/vi.png"
  },
  "AR": {
    "zh": "阿根廷",
    "en": "Argentina",
    "lat": -38.4,
    "lon": -63.6,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ar.png"
  },
  "BO": {
    "zh": "玻利维亚",
    "en": "Bolivia",
    "lat": -16.3,
    "lon": -63.6,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/bo.png"
  },
  "BR": {
    "zh": "巴西",
    "en": "Brazil",
    "lat": -10.8,
    "lon": -52.9,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/br.png"
  },
  "CL": {
    "zh": "智利",
    "en": "Chile",
    "lat": -35.7,
    "lon": -71.5,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/cl.png"
  },
  "CO": {
    "zh": "哥伦比亚",
    "en": "Colombia",
    "lat": 4.1,
    "lon": -72.9,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/co.png"
  },
  "EC": {
    "zh": "厄瓜多尔",
    "en": "Ecuador",
    "lat": -1.4,
    "lon": -78.2,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/ec.png"
  },
  "FK": {
    "zh": "福克兰群岛",
    "en": "Falkland Islands",
    "lat": -51.8,
    "lon": -59.5,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/fk.png"
  },
  "GF": {
    "zh": "法属圭亚那",
    "en": "French Guiana",
    "lat": 4,
    "lon": -53,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gf.png"
  },
  "GY": {
    "zh": "圭亚那",
    "en": "Guyana",
    "lat": 4.9,
    "lon": -58.9,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gy.png"
  },
  "PY": {
    "zh": "巴拉圭",
    "en": "Paraguay",
    "lat": -23.4,
    "lon": -58.4,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/py.png"
  },
  "PE": {
    "zh": "秘鲁",
    "en": "Peru",
    "lat": -9.2,
    "lon": -75,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/pe.png"
  },
  "SR": {
    "zh": "苏里南",
    "en": "Suriname",
    "lat": 4,
    "lon": -56,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/sr.png"
  },
  "UY": {
    "zh": "乌拉圭",
    "en": "Uruguay",
    "lat": -32.8,
    "lon": -56,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/uy.png"
  },
  "GS": {
    "zh": "南乔治亚和南桑威奇群岛",
    "en": "South Georgia and the South Sandwich Islands",
    "lat": -54.5,
    "lon": -37,
    "subregion": "南美",
    "continent": "拉丁美洲",
    "flag": "https://flagcdn.com/w320/gs.png"
  },
  "AU": {
    "zh": "澳大利亚",
    "en": "Australia",
    "lat": -25.7,
    "lon": 134.5,
    "subregion": "澳新",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/au.png"
  },
  "NF": {
    "zh": "诺福克岛",
    "en": "Norfolk Island",
    "lat": -29.04,
    "lon": 167.95,
    "subregion": "澳新",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/nf.png"
  },
  "CX": {
    "zh": "圣诞岛",
    "en": "Christmas Island",
    "lat": -10.49,
    "lon": 105.6,
    "subregion": "澳新",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/cx.png"
  },
  "CC": {
    "zh": "科科斯群岛",
    "en": "Cocos (Keeling) Islands",
    "lat": -12.17,
    "lon": 96.83,
    "subregion": "澳新",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/cc.png"
  },
  "FJ": {
    "zh": "斐济",
    "en": "Fiji",
    "lat": -17.7,
    "lon": 178,
    "subregion": "美拉尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/fj.png"
  },
  "NC": {
    "zh": "新喀里多尼亚",
    "en": "New Caledonia",
    "lat": -21.3,
    "lon": 165.5,
    "subregion": "美拉尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/nc.png"
  },
  "PG": {
    "zh": "巴布亚新几内亚",
    "en": "Papua New Guinea",
    "lat": -6.5,
    "lon": 145,
    "subregion": "美拉尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/pg.png"
  },
  "SB": {
    "zh": "所罗门群岛",
    "en": "Solomon Islands",
    "lat": -9.6,
    "lon": 160.2,
    "subregion": "美拉尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/sb.png"
  },
  "VU": {
    "zh": "瓦努阿图",
    "en": "Vanuatu",
    "lat": -16,
    "lon": 167.5,
    "subregion": "美拉尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/vu.png"
  },
  "FM": {
    "zh": "密克罗尼西亚联邦",
    "en": "Micronesia",
    "lat": 6.9,
    "lon": 158.2,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/fm.png"
  },
  "GU": {
    "zh": "关岛",
    "en": "Guam",
    "lat": 13.45,
    "lon": 144.78,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/gu.png"
  },
  "KI": {
    "zh": "基里巴斯",
    "en": "Kiribati",
    "lat": 1.9,
    "lon": -157.4,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/ki.png"
  },
  "MH": {
    "zh": "马绍尔群岛",
    "en": "Marshall Islands",
    "lat": 7.1,
    "lon": 171.2,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/mh.png"
  },
  "MP": {
    "zh": "北马里亚纳群岛",
    "en": "Northern Mariana Islands",
    "lat": 15.2,
    "lon": 145.7,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/mp.png"
  },
  "NR": {
    "zh": "瑙鲁",
    "en": "Nauru",
    "lat": -0.52,
    "lon": 166.93,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/nr.png"
  },
  "PW": {
    "zh": "帕劳",
    "en": "Palau",
    "lat": 7.5,
    "lon": 134.6,
    "subregion": "密克罗尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/pw.png"
  },
  "CK": {
    "zh": "库克群岛",
    "en": "Cook Islands",
    "lat": -21.2,
    "lon": -159.8,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/ck.png"
  },
  "PF": {
    "zh": "法属波利尼西亚",
    "en": "French Polynesia",
    "lat": -17.7,
    "lon": -149.4,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/pf.png"
  },
  "NU": {
    "zh": "纽埃",
    "en": "Niue",
    "lat": -19.05,
    "lon": -169.87,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/nu.png"
  },
  "PN": {
    "zh": "皮特凯恩群岛",
    "en": "Pitcairn Islands",
    "lat": -24.4,
    "lon": -128.3,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/pn.png"
  },
  "TK": {
    "zh": "托克劳",
    "en": "Tokelau",
    "lat": -9.2,
    "lon": -171.8,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/tk.png"
  },
  "TO": {
    "zh": "汤加",
    "en": "Tonga",
    "lat": -21.2,
    "lon": -175.2,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/to.png"
  },
  "TV": {
    "zh": "图瓦卢",
    "en": "Tuvalu",
    "lat": -7.5,
    "lon": 178,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/tv.png"
  },
  "WS": {
    "zh": "萨摩亚",
    "en": "Samoa",
    "lat": -13.8,
    "lon": -172.1,
    "subregion": "波利尼西亚",
    "continent": "大洋洲",
    "flag": "https://flagcdn.com/w320/ws.png"
  },
  "CA": {
    "zh": "加拿大",
    "en": "Canada",
    "lat": 56.1,
    "lon": -106.3,
    "subregion": "",
    "continent": "北美洲",
    "flag": "https://flagcdn.com/w320/ca.png"
  },
  "GL": {
    "zh": "格陵兰",
    "en": "Greenland",
    "lat": 71.7,
    "lon": -42.6,
    "subregion": "",
    "continent": "北美洲",
    "flag": "https://flagcdn.com/w320/gl.png"
  },
  "BM": {
    "zh": "百慕大",
    "en": "Bermuda",
    "lat": 32.3,
    "lon": -64.75,
    "subregion": "",
    "continent": "北美洲",
    "flag": "https://flagcdn.com/w320/bm.png"
  },
  "PM": {
    "zh": "圣皮埃尔和密克隆",
    "en": "Saint Pierre and Miquelon",
    "lat": 46.9,
    "lon": -56.3,
    "subregion": "",
    "continent": "北美洲",
    "flag": "https://flagcdn.com/w320/pm.png"
  }
};

// Continents keyed by Chinese name — read from _region/
const CONTINENTS = {
  "非洲": {
    "zh": "非洲",
    "en": "Africa",
    "lat": 8.8,
    "lon": 34.5
  },
  "亚洲": {
    "zh": "亚洲",
    "en": "Asia",
    "lat": 34,
    "lon": 100.6
  },
  "欧洲": {
    "zh": "欧洲",
    "en": "Europe",
    "lat": 54.5,
    "lon": 15.3
  },
  "拉丁美洲": {
    "zh": "拉丁美洲",
    "en": "Latin America and the Caribbean",
    "lat": -14.2,
    "lon": -60
  },
  "北美洲": {
    "zh": "北美洲",
    "en": "North America",
    "lat": 54.5,
    "lon": -105.3
  },
  "大洋洲": {
    "zh": "大洋洲",
    "en": "Oceania",
    "lat": -22.7,
    "lon": 140
  }
};

// Subregions keyed by Chinese name — read from _region/ (each linked to its continent)
const SUBREGIONS = {
  "澳新": {
    "zh": "澳新",
    "en": "Australia and New Zealand",
    "continent": "大洋洲"
  },
  "加勒比": {
    "zh": "加勒比",
    "en": "Caribbean",
    "continent": "拉丁美洲"
  },
  "中美洲": {
    "zh": "中美洲",
    "en": "Central America",
    "continent": "拉丁美洲"
  },
  "东亚": {
    "zh": "东亚",
    "en": "Eastern Asia",
    "continent": "亚洲"
  },
  "东欧": {
    "zh": "东欧",
    "en": "Eastern Europe",
    "continent": "欧洲"
  },
  "北非": {
    "zh": "北非",
    "en": "Northern Africa",
    "continent": "非洲"
  },
  "北欧": {
    "zh": "北欧",
    "en": "Northern Europe",
    "continent": "欧洲"
  },
  "南美": {
    "zh": "南美",
    "en": "South America",
    "continent": "拉丁美洲"
  },
  "南亚": {
    "zh": "南亚",
    "en": "Southern Asia",
    "continent": "亚洲"
  },
  "南欧": {
    "zh": "南欧",
    "en": "Southern Europe",
    "continent": "欧洲"
  },
  "西亚": {
    "zh": "西亚",
    "en": "Western Asia",
    "continent": "亚洲"
  },
  "西欧": {
    "zh": "西欧",
    "en": "Western Europe",
    "continent": "欧洲"
  }
};

// Color buckets — one per subregion (||continent) actually used by the 100 people
const REGIONS = {
  "西欧": {
    "label": "西欧",
    "color": "#4a90d9",
    "bg": "rgba(74, 144, 217, 0.15)"
  },
  "南欧": {
    "label": "南欧",
    "color": "#38b2a8",
    "bg": "rgba(56, 178, 168, 0.15)"
  },
  "北欧": {
    "label": "北欧",
    "color": "#2f4b8f",
    "bg": "rgba(47, 75, 143, 0.15)"
  },
  "东欧": {
    "label": "东欧",
    "color": "#7a6fd0",
    "bg": "rgba(122, 111, 208, 0.15)"
  },
  "西亚": {
    "label": "西亚",
    "color": "#e8a838",
    "bg": "rgba(232, 168, 56, 0.15)"
  },
  "南亚": {
    "label": "南亚",
    "color": "#e0673a",
    "bg": "rgba(224, 103, 58, 0.15)"
  },
  "东亚": {
    "label": "东亚",
    "color": "#e05252",
    "bg": "rgba(224, 82, 82, 0.15)"
  },
  "北非": {
    "label": "北非",
    "color": "#a0522d",
    "bg": "rgba(160, 82, 45, 0.15)"
  },
  "北美洲": {
    "label": "北美洲",
    "color": "#b8569e",
    "bg": "rgba(184, 86, 158, 0.15)"
  },
  "中美洲": {
    "label": "中美洲",
    "color": "#c86fa0",
    "bg": "rgba(200, 111, 160, 0.15)"
  },
  "加勒比": {
    "label": "加勒比",
    "color": "#c060a0",
    "bg": "rgba(192, 96, 160, 0.15)"
  },
  "南美": {
    "label": "南美",
    "color": "#d77fb0",
    "bg": "rgba(215, 127, 176, 0.15)"
  },
  "澳新": {
    "label": "澳新",
    "color": "#2ecc71",
    "bg": "rgba(46, 204, 113, 0.15)"
  }
};

const DOMAIN_LABELS = {
  Nature:  { label:"自然·科学", color:"#52a8e0" },
  Spirit:  { label:"思想·文化", color:"#9a6cd0" },
  Society: { label:"政治·社会", color:"#e5823c" },
};

const ROLE_LABELS = {
  Physicist:      "物理学家",
  Mathematician:  "数学家",
  Biologist:      "生物学家",
  Chemist:        "化学家",
  Astronomer:     "天文学家",
  Doctor:         "医学家",
  MedResearcher:  "医学研究者",
  Inventor:       "发明家",
  Industrialist:  "实业家",
  Philosopher:    "哲学家",
  SocialScientist:"社会科学家",
  Artist:         "艺术家",
  Author:         "作家",
  Composer:       "作曲家",
  Spiritual:      "宗教创始人",
  Clergy:         "宗教领袖",
  Theologian:     "神学家",
  Politician:     "政治家",
  General:        "军事家",
  Conqueror:      "征服者",
  Explorer:       "探险家",
};

// Per-role node colors for map + timeline. Built on the role/domain tree
// (role/{Domain}/{Group}/{Role}): domain = hue family, group = a band within it,
// role = a tint inside that band. Nature splits at the group level —
// Science=蓝, Tech=绿; Spirit=紫; Society=橙.
const ROLE_COLORS = {
  // ── Nature / Science — 蓝 ──
  Physicist:"#4a90d9", Astronomer:"#6c8cff", Mathematician:"#4aa6e0",
  MedResearcher:"#3fa8d4", Doctor:"#62c0e4", Chemist:"#45bcc8", Biologist:"#52c8c2",
  // ── Nature / Tech — 绿 ──
  Inventor:"#4cb87f", Industrialist:"#84c25a",
  // ── Spirit — 紫 ──
  //   Creative — 紫罗兰
  Artist:"#a06cd8", Author:"#ba8ae4", Composer:"#8d5fd0",
  //   Humanities — 靛紫
  Philosopher:"#7a6cce", SocialScientist:"#6a5cc2",
  //   Religion — 品红紫
  Spiritual:"#bb5cc8", Clergy:"#c970d4", Theologian:"#a448b0",
  // ── Society — 橙 ──
  //   Governance — 橙
  Politician:"#e89240", General:"#d07828",
  //   Frontier — 橘红/珊瑚
  Conqueror:"#e5673a", Explorer:"#ef8c50",
};

const ALL_TAGS = [
  "role/Nature/Science/Astronomer",
  "role/Nature/Science/Biologist",
  "role/Nature/Science/Chemist",
  "role/Nature/Science/Doctor",
  "role/Nature/Science/Mathematician",
  "role/Nature/Science/MedResearcher",
  "role/Nature/Science/Physicist",
  "role/Nature/Tech/Industrialist",
  "role/Nature/Tech/Inventor",
  "role/Society/Frontier/Conqueror",
  "role/Society/Frontier/Explorer",
  "role/Society/Governance/General",
  "role/Society/Governance/Politician",
  "role/Spirit/Creative/Artist",
  "role/Spirit/Creative/Author",
  "role/Spirit/Creative/Composer",
  "role/Spirit/Humanities/Philosopher",
  "role/Spirit/Humanities/SocialScientist",
  "role/Spirit/Religion/Clergy",
  "role/Spirit/Religion/Spiritual",
  "role/Spirit/Religion/Theologian"
];
