// node enrich-data.js
// Merges the complete country reference (country-ref.js) into the existing
// data.js WITHOUT touching the person data. Use this when the Obsidian notes
// can't be rebuilt by build-data.js (e.g. THE100 chapter files lost their
// rank/about frontmatter). build-data.js remains the canonical generator and
// already contains the same merge logic for when the vault is rebuildable.

const fs = require('fs');
const path = require('path');
const COUNTRY_REF = require('./country-ref.js');

const OUT_FILE = path.join(__dirname, 'data.js');

// Load current data.js values (top-level const/let don't attach to the VM
// context, so re-export them into a global at the end of the script).
const ctx = {};
const vm = require('vm');
vm.createContext(ctx);
vm.runInContext(
  fs.readFileSync(OUT_FILE, 'utf8') +
  '\n;globalThis.__data = { PERSONS, COUNTRIES, CONTINENTS, SUBREGIONS, REGIONS, DOMAIN_LABELS, ROLE_LABELS, ALL_TAGS };',
  ctx
);
const D = ctx.__data;
const PERSONS = D.PERSONS;
const countries = { ...D.COUNTRIES };
const continents = D.CONTINENTS;
const subregions = D.SUBREGIONS;
const DOMAIN_LABELS = D.DOMAIN_LABELS;
const ROLE_LABELS = D.ROLE_LABELS;
const allTags = D.ALL_TAGS;

// ── Merge country reference (existing entries win, fill blanks) ──
let added = 0, filled = 0;
for (const [iso, rc] of Object.entries(COUNTRY_REF.COUNTRIES)) {
  if (!countries[iso]) { countries[iso] = { ...rc }; added++; }
  else {
    for (const k of ['zh', 'en', 'lat', 'lon', 'subregion', 'continent', 'flag']) {
      const v = countries[iso][k];
      if (v === '' || v === null || v === undefined) { countries[iso][k] = rc[k]; filled++; }
    }
  }
}

// ── Rebuild REGIONS colors (same palette as build-data.js) ──
const REGION_COLOR = {
  '西欧':'#4a90d9', '南欧':'#38b2a8', '北欧':'#2f4b8f', '东欧':'#7a6fd0', '欧洲':'#4a90d9',
  '西亚':'#e8a838', '南亚':'#e0673a', '东亚':'#e05252', '亚洲':'#e8a838',
  '北非':'#a0522d', '非洲':'#a0522d',
  '北美洲':'#b8569e', '中美洲':'#c86fa0', '加勒比':'#c060a0', '南美':'#d77fb0', '拉丁美洲':'#d77fb0',
  '澳新':'#2ecc71', '大洋洲':'#27ae60',
};
const REGION_ORDER = [
  '西欧','南欧','北欧','东欧','欧洲',
  '西亚','南亚','东亚','亚洲',
  '北非','非洲',
  '北美洲','中美洲','加勒比','南美','拉丁美洲',
  '澳新','大洋洲',
];
function hexToRgba(hex, a) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${a})`;
}
const usedRegions = new Set(PERSONS.map(p => p.region).filter(Boolean));
const colorRegions = new Set([...usedRegions, ...Object.keys(subregions)]);
const orderedRegions = [...new Set([
  ...REGION_ORDER.filter(k => colorRegions.has(k)),
  ...[...colorRegions].filter(k => !REGION_ORDER.includes(k)),
])];
const regions = {};
for (const key of orderedRegions) {
  const color = REGION_COLOR[key] || '#888888';
  regions[key] = { label: key, color, bg: hexToRgba(color, 0.15) };
}

// ── Write data.js (same shape as build-data.js) ──
const js = `// Auto-generated by build-data.js — do not edit manually
const PERSONS = ${JSON.stringify(PERSONS, null, 2)};

// Countries keyed by ISO code — _region/ notes merged with country-ref.js (complete)
const COUNTRIES = ${JSON.stringify(countries, null, 2)};

// Continents keyed by Chinese name — read from _region/
const CONTINENTS = ${JSON.stringify(continents, null, 2)};

// Subregions keyed by Chinese name — read from _region/ (each linked to its continent)
const SUBREGIONS = ${JSON.stringify(subregions, null, 2)};

// Color buckets — every region selectable in the filter dropdown
const REGIONS = ${JSON.stringify(regions, null, 2)};

const DOMAIN_LABELS = ${JSON.stringify(DOMAIN_LABELS, null, 2)};

const ROLE_LABELS = ${JSON.stringify(ROLE_LABELS, null, 2)};

const ALL_TAGS = ${JSON.stringify(allTags, null, 2)};
`;

fs.writeFileSync(OUT_FILE, js, 'utf8');
console.log(`data.js enriched — persons: ${PERSONS.length}, countries: ${Object.keys(countries).length} (added ${added}, filled ${filled}), regions: ${Object.keys(regions).length}`);
